import Head from 'next/head'
import { Container, Logo } from '@/styles/home.module'
import 'animate.css';

export default function LoadingScreen() {
  return (
    <>
      <Head>
        <title>TweetMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Logo
          className='animate__animated animate__pulse animate__infinite'
          src="/images/logo.png"
          alt="Logo"
          width={120}
          height={100}
          priority
        />
      </Container>
    </>
  )
}
